"""Tests for scope filtering (--include, --exclude, --review, --scope-file)."""

import textwrap
from pathlib import Path

import pytest
import yaml

from mcp_anything.models.analysis import AnalysisResult, Capability, IPCType, ParameterSpec
from mcp_anything.pipeline.scope import apply_scope, read_scope_file, write_scope_file


def _make_analysis(capabilities: list[Capability]) -> AnalysisResult:
    return AnalysisResult(
        app_name="test-app",
        app_description="Test application",
        capabilities=capabilities,
        primary_ipc=IPCType.PROTOCOL,
    )


def _cap(name: str, source: str = "", description: str = "", category: str = "api") -> Capability:
    return Capability(
        name=name,
        description=description or f"Description for {name}",
        category=category,
        source_file=source,
        ipc_type=IPCType.PROTOCOL,
    )


@pytest.fixture
def sample_analysis():
    return _make_analysis([
        _cap("get_users", "/api/v2/users", "GET /api/v2/users - List users"),
        _cap("get_user", "/api/v2/users/{id}", "GET /api/v2/users/{id} - Get user"),
        _cap("create_user", "/api/v2/users", "POST /api/v2/users - Create user"),
        _cap("get_internal_metrics", "/internal/metrics", "GET /internal/metrics"),
        _cap("get_internal_health", "/internal/health", "GET /internal/health"),
        _cap("get_reports", "/api/v1/reports", "GET /api/v1/reports - Legacy reports"),
        _cap("debug_dump", "debug/dump.py", "Debug dump endpoint", category="debug"),
    ])


# --- write_scope_file / read_scope_file ---

class TestScopeFileIO:
    def test_write_read_roundtrip(self, sample_analysis, tmp_path):
        scope_path = tmp_path / "scope.yaml"
        write_scope_file(sample_analysis, scope_path)

        assert scope_path.exists()
        doc = read_scope_file(scope_path)

        assert "capabilities" in doc
        assert len(doc["capabilities"]) == 7
        assert all("enabled" not in entry for entry in doc["capabilities"])
        assert doc["include_patterns"] == []
        assert doc["exclude_patterns"] == []

    def test_write_includes_metadata(self, tmp_path):
        analysis = _make_analysis([
            Capability(
                name="get_items",
                description="GET /api/items",
                category="api",
                source_file="routes/items.py",
                ipc_type=IPCType.PROTOCOL,
            ),
        ])
        scope_path = tmp_path / "scope.yaml"
        write_scope_file(analysis, scope_path)

        doc = read_scope_file(scope_path)
        entry = doc["capabilities"][0]
        assert entry["name"] == "get_items"
        assert entry["description"] == "GET /api/items"
        assert entry["source"] == "routes/items.py"
        assert entry["category"] == "api"

    def test_write_creates_parent_dirs(self, tmp_path):
        scope_path = tmp_path / "deep" / "nested" / "scope.yaml"
        analysis = _make_analysis([_cap("test_cap")])
        write_scope_file(analysis, scope_path)
        assert scope_path.exists()

    def test_read_invalid_file(self, tmp_path):
        bad_file = tmp_path / "bad.yaml"
        bad_file.write_text("just a string")
        with pytest.raises(ValueError, match="expected a YAML mapping"):
            read_scope_file(bad_file)

    def test_scope_file_has_header_comments(self, tmp_path):
        analysis = _make_analysis([_cap("test_cap")])
        scope_path = tmp_path / "scope.yaml"
        write_scope_file(analysis, scope_path)

        content = scope_path.read_text()
        assert "Generated by mcp-anything" in content
        assert "--resume" in content


# --- apply_scope with include patterns ---

class TestIncludePatterns:
    def test_include_by_name(self, sample_analysis):
        result = apply_scope(sample_analysis, include_patterns=["get_user*"])
        names = [c.name for c in result.capabilities]
        assert "get_users" in names
        assert "get_user" in names
        assert "create_user" not in names
        assert "get_internal_metrics" not in names

    def test_include_by_source_path(self, sample_analysis):
        result = apply_scope(sample_analysis, include_patterns=["/api/v2/*"])
        names = [c.name for c in result.capabilities]
        assert "get_users" in names
        assert "get_user" in names
        assert "create_user" in names
        assert "get_internal_metrics" not in names
        assert "get_reports" not in names

    def test_include_by_description(self, sample_analysis):
        result = apply_scope(sample_analysis, include_patterns=["*List users*"])
        names = [c.name for c in result.capabilities]
        assert names == ["get_users"]

    def test_include_multiple_patterns(self, sample_analysis):
        result = apply_scope(
            sample_analysis,
            include_patterns=["get_users", "get_reports"],
        )
        names = [c.name for c in result.capabilities]
        assert set(names) == {"get_users", "get_reports"}

    def test_include_no_match(self, sample_analysis):
        result = apply_scope(sample_analysis, include_patterns=["nonexistent*"])
        assert len(result.capabilities) == 0


# --- apply_scope with exclude patterns ---

class TestExcludePatterns:
    def test_exclude_by_name(self, sample_analysis):
        result = apply_scope(sample_analysis, exclude_patterns=["*internal*"])
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "get_internal_health" not in names
        assert "get_users" in names

    def test_exclude_by_source_path(self, sample_analysis):
        result = apply_scope(sample_analysis, exclude_patterns=["/internal/*"])
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "get_internal_health" not in names

    def test_exclude_by_description(self, sample_analysis):
        result = apply_scope(sample_analysis, exclude_patterns=["*Legacy*"])
        names = [c.name for c in result.capabilities]
        assert "get_reports" not in names
        assert "get_users" in names

    def test_exclude_multiple_patterns(self, sample_analysis):
        result = apply_scope(
            sample_analysis,
            exclude_patterns=["*internal*", "debug_*"],
        )
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "debug_dump" not in names
        assert "get_users" in names


# --- include + exclude combined ---

class TestCombinedPatterns:
    def test_include_then_exclude(self, sample_analysis):
        result = apply_scope(
            sample_analysis,
            include_patterns=["get_*"],
            exclude_patterns=["*internal*"],
        )
        names = [c.name for c in result.capabilities]
        assert "get_users" in names
        assert "get_user" in names
        assert "get_reports" in names
        assert "get_internal_metrics" not in names
        assert "create_user" not in names


# --- apply_scope with scope file ---

class TestScopeFile:
    def test_scope_file_disable_capabilities(self, sample_analysis, tmp_path):
        scope_path = tmp_path / "scope.yaml"
        write_scope_file(sample_analysis, scope_path)

        # Edit: disable internal capabilities
        doc = read_scope_file(scope_path)
        for entry in doc["capabilities"]:
            if "internal" in entry["name"]:
                entry["enabled"] = False
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        result = apply_scope(sample_analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "get_internal_health" not in names
        assert "get_users" in names

    def test_scope_file_with_patterns(self, tmp_path):
        analysis = _make_analysis([
            _cap("get_users", "/api/users"),
            _cap("get_admin", "/admin/users"),
            _cap("get_debug", "/debug/info"),
        ])

        scope_path = tmp_path / "scope.yaml"
        doc = {
            "include_patterns": [],
            "exclude_patterns": ["/admin/*", "/debug/*"],
            "capabilities": [],
        }
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        result = apply_scope(analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]
        assert names == ["get_users"]

    def test_scope_file_explicit_enable_overrides_exclude_pattern(self, tmp_path):
        """Explicitly enabled capabilities bypass pattern filters."""
        analysis = _make_analysis([
            _cap("get_internal_metrics", "/internal/metrics"),
            _cap("get_internal_health", "/internal/health"),
        ])

        scope_path = tmp_path / "scope.yaml"
        doc = {
            "include_patterns": [],
            "exclude_patterns": ["*internal*"],
            "capabilities": [
                {"name": "get_internal_metrics", "enabled": True},
            ],
        }
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        result = apply_scope(analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]
        # Explicitly enabled: kept despite exclude pattern
        assert "get_internal_metrics" in names
        # Not in capabilities list: excluded by pattern
        assert "get_internal_health" not in names

    def test_scope_file_combined_with_cli_patterns(self, sample_analysis, tmp_path):
        """CLI patterns are additive with scope file patterns."""
        scope_path = tmp_path / "scope.yaml"
        doc = {
            "include_patterns": [],
            "exclude_patterns": ["*internal*"],
            "capabilities": [],
        }
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        result = apply_scope(
            sample_analysis,
            exclude_patterns=["debug_*"],
            scope_file=scope_path,
        )
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "debug_dump" not in names
        assert "get_users" in names

    def test_scope_file_nonexistent_is_skipped(self, sample_analysis, tmp_path):
        result = apply_scope(
            sample_analysis,
            scope_file=tmp_path / "nonexistent.yaml",
        )
        assert len(result.capabilities) == len(sample_analysis.capabilities)


# --- edge cases ---

class TestEdgeCases:
    def test_empty_analysis(self):
        analysis = _make_analysis([])
        result = apply_scope(analysis, include_patterns=["*"])
        assert len(result.capabilities) == 0

    def test_all_excluded(self, sample_analysis):
        result = apply_scope(sample_analysis, exclude_patterns=["*"])
        assert len(result.capabilities) == 0

    def test_no_filters_returns_all(self, sample_analysis):
        result = apply_scope(sample_analysis)
        assert len(result.capabilities) == len(sample_analysis.capabilities)

    def test_original_analysis_not_mutated(self, sample_analysis):
        original_count = len(sample_analysis.capabilities)
        apply_scope(sample_analysis, exclude_patterns=["*"])
        assert len(sample_analysis.capabilities) == original_count

    def test_capabilities_without_source_file(self):
        analysis = _make_analysis([
            _cap("bare_cap", source="", description="A bare capability"),
        ])
        result = apply_scope(analysis, include_patterns=["bare_*"])
        assert len(result.capabilities) == 1

    def test_scope_file_missing_capabilities_key(self, tmp_path):
        scope_path = tmp_path / "scope.yaml"
        doc = {"exclude_patterns": ["*internal*"]}
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        analysis = _make_analysis([
            _cap("get_users", "/api/users"),
            _cap("get_internal", "/internal/x"),
        ])
        result = apply_scope(analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]
        assert "get_users" in names
        assert "get_internal" not in names


# --- integration: review + resume workflow ---

class TestReviewResumeWorkflow:
    def test_full_review_resume_cycle(self, sample_analysis, tmp_path):
        """Simulate: analyze --review → user edits → --resume."""
        scope_path = tmp_path / "scope.yaml"

        # Step 1: write scope file (what --review does)
        write_scope_file(sample_analysis, scope_path)
        assert scope_path.exists()

        # Step 2: user edits — disables internal + debug, keeps the rest
        doc = read_scope_file(scope_path)
        for entry in doc["capabilities"]:
            if "internal" in entry["name"] or "debug" in entry["name"]:
                entry["enabled"] = False
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        # Step 3: resume applies the scope file
        result = apply_scope(sample_analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]

        assert "get_users" in names
        assert "get_user" in names
        assert "create_user" in names
        assert "get_reports" in names
        assert "get_internal_metrics" not in names
        assert "get_internal_health" not in names
        assert "debug_dump" not in names
        assert len(result.capabilities) == 4

    def test_review_then_add_exclude_patterns(self, sample_analysis, tmp_path):
        """User edits scope.yaml to add exclude patterns instead of per-cap."""
        scope_path = tmp_path / "scope.yaml"
        write_scope_file(sample_analysis, scope_path)

        doc = read_scope_file(scope_path)
        doc["exclude_patterns"] = ["/internal/*", "debug_*"]
        # Don't touch per-capability flags — all stay enabled
        with open(scope_path, "w") as f:
            yaml.dump(doc, f)

        result = apply_scope(sample_analysis, scope_file=scope_path)
        names = [c.name for c in result.capabilities]
        assert "get_internal_metrics" not in names
        assert "get_internal_health" not in names
        assert "debug_dump" not in names
        assert "get_users" in names
