"""TypeScript/mcp-use emit phase (Phase 3, TypeScript target)."""

import json
import subprocess
import sys
from pathlib import Path

from mcp_anything.emit.base import EmitPhase
from mcp_anything.models.design import ServerDesign
from mcp_anything.pipeline.context import PipelineContext


class TypeScriptMcpUseEmitPhase(EmitPhase):
    """Emits a TypeScript/mcp-use MCP server from a ServerDesign."""

    name = "emit"
    backend_target = "mcp-use"

    async def execute(self, ctx: PipelineContext) -> None:
        design = self._load_design(ctx)
        output_dir = Path(ctx.manifest.output_dir) / "ts"
        output_dir.mkdir(parents=True, exist_ok=True)

        emitter = TypeScriptMcpUseEmitter(design, output_dir)
        generated = emitter.emit_all()

        # Optional TypeScript compile check
        if self._tsc_available():
            ctx.console.print("    Type-checking generated TypeScript...")
            errors = self._validate_typescript(output_dir)
            if errors:
                ctx.console.print(f"    [yellow]TypeScript warnings: {errors[:3]}[/yellow]")

        ctx.manifest.generated_files.extend([f"ts/{f}" for f in generated])
        ctx.console.print(f"    Generated {len(generated)} TypeScript files")

        contract_results = self.validate_contract(design, output_dir)
        ctx.manifest.contract_check_results = [c.model_dump() for c in contract_results]
        failed = [c for c in contract_results if not c.passed]
        if failed:
            ctx.console.print(
                f"    [yellow]Contract warnings (TS): {[c.id for c in failed]}[/yellow]"
            )

        ctx.save_manifest()

    def _load_design(self, ctx: PipelineContext) -> ServerDesign:
        if ctx.manifest.design:
            return ctx.manifest.design
        if ctx.manifest.tool_spec:
            return ServerDesign.model_validate(ctx.manifest.tool_spec)
        raise RuntimeError("No design available for TypeScript code generation.")

    def _tsc_available(self) -> bool:
        try:
            result = subprocess.run(
                ["tsc", "--version"],
                capture_output=True,
                timeout=5,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _validate_typescript(self, output_dir: Path) -> list[str]:
        tsconfig = output_dir / "tsconfig.json"
        if not tsconfig.exists():
            return []
        try:
            result = subprocess.run(
                ["tsc", "--noEmit", "--project", str(tsconfig)],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=output_dir,
            )
            if result.returncode != 0:
                return result.stdout.splitlines()[:10]
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass
        return []


class TypeScriptMcpUseEmitter:
    """Renders TypeScript/mcp-use server files from a ServerDesign."""

    def __init__(self, design: ServerDesign, output_dir: Path) -> None:
        self.design = design
        self.output_dir = output_dir
        self.generated_files: list[str] = []

    def emit_all(self) -> list[str]:
        self._emit_server()
        self._emit_tools()
        self._emit_discovery()
        self._emit_telemetry()
        self._emit_dockerfile()
        self._emit_package_json()
        self._emit_tsconfig()
        return self.generated_files

    def _write(self, rel_path: str, content: str) -> None:
        full = self.output_dir / rel_path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content)
        self.generated_files.append(rel_path)

    def _emit_server(self) -> None:
        tool_imports = "\n".join(
            f'import {{ {t.name} }} from "./tools/{t.name}";'
            for t in self.design.tools
        )
        tool_registrations = "\n".join(
            f"  server.tool({t.name});"
            for t in self.design.tools
        )
        content = f'''/**
 * MCP server for {self.design.server_name}
 * Generated by mcp-anything
 */
import {{ McpServer }} from "@modelcontextprotocol/sdk/server/mcp.js";
import {{ StdioServerTransport }} from "@modelcontextprotocol/sdk/server/stdio.js";
import {{ getDiscoveryInfo }} from "./discovery.js";
import {{ recordCall }} from "./telemetry.js";
{tool_imports}

const server = new McpServer({{
  name: "{self.design.server_name}",
  version: "1.0.0",
  description: `{self.design.server_description}`,
}});

{tool_registrations}

// /.well-known/mcp discovery endpoint (CONTRACT C-01..C-03)
server.resource("mcp-discovery", "/.well-known/mcp", async () => {{
  return {{
    contents: [{{
      uri: "/.well-known/mcp",
      mimeType: "application/json",
      text: JSON.stringify(getDiscoveryInfo()),
    }}],
  }};
}});

async function main() {{
  const transport = process.env.MCP_TRANSPORT ?? "{self.design.transport}";
  if (transport === "http") {{
    // HTTP transport: wire into an Express server externally
    console.error("HTTP transport: mount server.requestHandler() in your HTTP server");
    process.exit(1);
  }}
  const t = new StdioServerTransport();
  await server.connect(t);
}}

main().catch(console.error);
'''
        self._write("src/server.ts", content)

    def _emit_tools(self) -> None:
        for tool in self.design.tools:
            params_schema = self._render_zod_schema(tool)
            impl = tool.impl
            call_code = self._render_call(tool)

            content = f'''/**
 * Tool: {tool.name}
 * {tool.description}
 */
import {{ z }} from "zod";
import {{ recordCall }} from "../telemetry.js";

export const {tool.name} = {{
  name: "{tool.name}",
  description: `{tool.description}`,
  parameters: z.object({{
{params_schema}
  }}),
  execute: async (params: any): Promise<any> => {{
    const start = Date.now();
    try {{
{call_code}
    }} finally {{
      recordCall("{tool.name}", Date.now() - start, "ok");
    }}
  }},
}};
'''
            self._write(f"src/tools/{tool.name}.ts", content)

    def _render_zod_schema(self, tool) -> str:
        lines = []
        for p in tool.parameters:
            z_type = self._to_zod_type(p.type)
            if not p.required:
                z_type = f"{z_type}.optional()"
            lines.append(
                f"    {json.dumps(p.name)}: {z_type}.describe({json.dumps(p.description)}),"
            )
        return "\n".join(lines)

    def _render_call(self, tool) -> str:
        impl = tool.impl

        if impl.strategy == "http_call" and impl.http_method and impl.http_path:
            base_url_env = f"{self.design.server_name.upper().replace('-','_')}_BASE_URL"
            path = impl.http_path
            method = impl.http_method.upper()
            constants = json.dumps(dict(impl.http_query_constants))
            param_meta = {}
            for p in tool.parameters:
                if p.name == "verbose":
                    continue
                mapping = impl.arg_mapping.get(p.name, {})
                style = mapping.get("style") or getattr(p, "location", "") or "query"
                if style not in {"path", "body", "query"}:
                    style = "query"
                param_meta[p.name] = {
                    "style": style,
                    "apiName": mapping.get("api_name") or getattr(p, "api_name", "") or p.name,
                }
            param_meta_json = json.dumps(param_meta)
            return f'''      const baseUrl = process.env["{base_url_env}"] ?? "http://localhost:8000";
      const url = new URL(`${{baseUrl}}{path}`);
      const bodyFields: Record<string, unknown> = {{}};
      const paramMeta: Record<string, {{ style: string; apiName: string }}> = {param_meta_json};
      for (const [k, v] of Object.entries(params)) {{
        if (v == null || k === "verbose") continue;
        const meta = paramMeta[k] ?? {{ style: "query", apiName: k }};
        if (meta.style === "path") {{
          url.pathname = url.pathname.replace(`{{${{meta.apiName}}}}`, encodeURIComponent(String(v)));
        }} else if (meta.style === "body") {{
          bodyFields[meta.apiName] = v;
        }} else {{
          url.searchParams.set(meta.apiName, String(v));
        }}
      }}
      for (const [k, v] of Object.entries({constants})) {{
        url.searchParams.set(k, String(v));
      }}
      const hasBody = Object.keys(bodyFields).length > 0;
      const resp = await fetch(url.toString(), {{
        method: "{method}",
        headers: hasBody ? {{ "Content-Type": "application/json" }} : undefined,
        body: hasBody ? JSON.stringify(bodyFields) : undefined,
      }});
      if (!resp.ok) throw new Error(`HTTP ${{resp.status}}: ${{await resp.text()}}`);
      const result = await resp.json();
      if (params.verbose) return {{ data: result, _meta: {{ status: resp.status }} }};
      return result;'''

        if impl.strategy == "cli_subcommand" and impl.cli_subcommand:
            bin_env = f"{self.design.server_name.upper().replace('-','_')}_BIN"
            default_bin = self.design.server_name
            return f'''      const {{ spawn }} = await import("node:child_process");
      const binary = process.env["{bin_env}"] ?? "{default_bin}";
      const args: string[] = ["{impl.cli_subcommand}"];
      for (const [k, v] of Object.entries(params)) {{
        if (v == null || k === "verbose") continue;
        const flag = `--${{k.replace(/_/g, "-")}}`;
        if (typeof v === "boolean") {{ if (v) args.push(flag); }}
        else args.push(flag, String(v));
      }}
      const result: any = await new Promise((resolve, reject) => {{
        const proc = spawn(binary, args);
        let stdout = "", stderr = "";
        proc.stdout.on("data", (d: Buffer) => stdout += d.toString());
        proc.stderr.on("data", (d: Buffer) => stderr += d.toString());
        proc.on("close", (code: number) => resolve({{ stdout, stderr, returncode: code }}));
        proc.on("error", reject);
      }});
      if (params.verbose) return result;
      return {{ output: result.stdout || result.stderr, returncode: result.returncode }};'''

        if impl.strategy == "grpc_call" and impl.grpc_service and impl.grpc_method:
            return f'''      // gRPC requires generated TypeScript stubs (e.g. via @grpc/proto-loader).
      // Configure {self.design.server_name.upper().replace("-", "_")}_GRPC_TARGET and wire your stub here.
      throw new Error("gRPC tool '{tool.name}' ({impl.grpc_service}.{impl.grpc_method}) requires a TypeScript gRPC client. Generate stubs and override this method.");'''

        return f'''      throw new Error("Tool '{tool.name}' has no executable strategy. Configure a data source (OpenAPI/gRPC) or implement this tool manually.");'''

    def _to_zod_type(self, t: str) -> str:
        mapping = {
            "string": "z.string()",
            "integer": "z.number().int()",
            "boolean": "z.boolean()",
            "array": "z.array(z.unknown())",
            "object": "z.record(z.unknown())",
            "number": "z.number()",
        }
        return mapping.get(t, "z.string()")

    def _emit_discovery(self) -> None:
        tool_list = json.dumps(
            [{"name": t.name, "description": t.description[:80]} for t in self.design.tools],
            indent=2,
        )
        groups = json.dumps(
            [{"name": g.name, "disclosure_level": g.disclosure_level} for g in self.design.tool_groups],
            indent=2,
        )
        content = f'''/**
 * Discovery endpoint data (CONTRACT C-01..C-03)
 */

const TOOLS = {tool_list};
const GROUPS = {groups};

export function getDiscoveryInfo() {{
  return {{
    server_name: "{self.design.server_name}",
    version: "1.0.0",
    tool_count: TOOLS.length,
    tool_groups: GROUPS,
    tools: TOOLS,
  }};
}}
'''
        self._write("src/discovery.ts", content)

    def _emit_telemetry(self) -> None:
        content = '''/**
 * Anonymized per-call telemetry (CONTRACT C-19, C-20)
 * Logs tool name, latency, and status only. Never logs parameter values.
 * Set MCP_TELEMETRY_ENDPOINT to enable remote reporting.
 */

const ENDPOINT = process.env["MCP_TELEMETRY_ENDPOINT"] ?? "";

export function recordCall(tool: string, latencyMs: number, status: string): void {
  console.error(JSON.stringify({ tool, latency_ms: latencyMs, status }));
  if (ENDPOINT) {
    sendRemote(tool, latencyMs, status).catch(() => {}); // must never break tool execution
  }
}

async function sendRemote(tool: string, latencyMs: number, status: string): Promise<void> {
  await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ tool, latency_ms: latencyMs, status }),
    signal: AbortSignal.timeout(1000),
  });
}
'''
        self._write("src/telemetry.ts", content)

    def _emit_dockerfile(self) -> None:
        content = f'''# Generated Dockerfile for {self.design.server_name} (TypeScript)
# CONTRACT C-17, C-18: no embedded secrets; reads API keys from environment at runtime.
FROM node:20-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --production

COPY . .
RUN npm run build

EXPOSE 8000

ENV MCP_TRANSPORT=http

CMD ["node", "dist/server.js"]
'''
        self._write("Dockerfile", content)

    def _emit_package_json(self) -> None:
        pkg = {
            "name": self.design.server_name,
            "version": "1.0.0",
            "description": self.design.server_description[:80],
            "type": "module",
            "main": "dist/server.js",
            "scripts": {
                "build": "tsc",
                "start": "node dist/server.js",
                "dev": "ts-node src/server.ts",
            },
            "dependencies": {
                "@modelcontextprotocol/sdk": "^1.0.0",
                "mcp-use": "^0.1.0",
                "zod": "^3.22.0",
            },
            "devDependencies": {
                "typescript": "^5.3.0",
                "@types/node": "^20.0.0",
                "ts-node": "^10.9.0",
            },
        }
        self._write("package.json", json.dumps(pkg, indent=2))

    def _emit_tsconfig(self) -> None:
        tsconfig = {
            "compilerOptions": {
                "target": "ES2022",
                "module": "NodeNext",
                "moduleResolution": "NodeNext",
                "strict": True,
                "outDir": "dist",
                "rootDir": "src",
                "declaration": True,
                "esModuleInterop": True,
            },
            "include": ["src/**/*"],
            "exclude": ["node_modules", "dist"],
        }
        self._write("tsconfig.json", json.dumps(tsconfig, indent=2))
