"""TypeScript/mcp-use emit phase (Phase 3, TypeScript target)."""

import json
import subprocess
import sys
from pathlib import Path

from mcp_anything.emit.base import EmitPhase
from mcp_anything.models.design import ServerDesign
from mcp_anything.pipeline.context import PipelineContext


class TypeScriptMcpUseEmitPhase(EmitPhase):
    """Emits a TypeScript/mcp-use MCP server from a ServerDesign."""

    name = "emit"
    backend_target = "mcp-use"

    async def execute(self, ctx: PipelineContext) -> None:
        design = self._load_design(ctx)
        output_dir = Path(ctx.manifest.output_dir) / "ts"
        output_dir.mkdir(parents=True, exist_ok=True)

        emitter = TypeScriptMcpUseEmitter(design, output_dir)
        generated = emitter.emit_all()

        # Optional TypeScript compile check
        if self._tsc_available():
            ctx.console.print("    Type-checking generated TypeScript...")
            errors = self._validate_typescript(output_dir)
            if errors:
                ctx.console.print(f"    [yellow]TypeScript warnings: {errors[:3]}[/yellow]")

        ctx.manifest.generated_files.extend([f"ts/{f}" for f in generated])
        ctx.console.print(f"    Generated {len(generated)} TypeScript files")

        contract_results = self.validate_contract(design, output_dir)
        ctx.manifest.contract_check_results = [c.model_dump() for c in contract_results]
        failed = [c for c in contract_results if not c.passed]
        if failed:
            ctx.console.print(
                f"    [yellow]Contract warnings (TS): {[c.id for c in failed]}[/yellow]"
            )

        ctx.save_manifest()

    def _load_design(self, ctx: PipelineContext) -> ServerDesign:
        if ctx.manifest.design:
            return ctx.manifest.design
        if ctx.manifest.tool_spec:
            return ServerDesign.model_validate(ctx.manifest.tool_spec)
        raise RuntimeError("No design available for TypeScript code generation.")

    def _tsc_available(self) -> bool:
        try:
            result = subprocess.run(
                ["tsc", "--version"],
                capture_output=True,
                timeout=5,
            )
            return result.returncode == 0
        except (FileNotFoundError, subprocess.TimeoutExpired):
            return False

    def _validate_typescript(self, output_dir: Path) -> list[str]:
        tsconfig = output_dir / "tsconfig.json"
        if not tsconfig.exists():
            return []
        try:
            result = subprocess.run(
                ["tsc", "--noEmit", "--project", str(tsconfig)],
                capture_output=True,
                text=True,
                timeout=30,
                cwd=output_dir,
            )
            if result.returncode != 0:
                return result.stdout.splitlines()[:10]
        except (subprocess.TimeoutExpired, FileNotFoundError):
            pass
        return []


class TypeScriptMcpUseEmitter:
    """Renders TypeScript/mcp-use server files from a ServerDesign."""

    def __init__(self, design: ServerDesign, output_dir: Path) -> None:
        self.design = design
        self.output_dir = output_dir
        self.generated_files: list[str] = []

    def emit_all(self) -> list[str]:
        self._emit_compact()
        self._emit_server()
        self._emit_tools()
        self._emit_discovery()
        self._emit_telemetry()
        self._emit_dockerfile()
        self._emit_package_json()
        self._emit_tsconfig()
        return self.generated_files

    def _write(self, rel_path: str, content: str) -> None:
        full = self.output_dir / rel_path
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content)
        self.generated_files.append(rel_path)

    def _emit_server(self) -> None:
        tool_imports = "\n".join(
            f'import * as {t.name} from "./tools/{t.name}.js";'
            for t in self.design.tools
        )
        tool_registrations = "\n".join(
            f"server.tool({t.name}.config, {t.name}.handler);"
            for t in self.design.tools
        )
        content = f'''/**
 * MCP server for {self.design.server_name}
 * Generated by mcp-anything
 */
import {{ MCPServer, object }} from "mcp-use";
import {{ getDiscoveryInfo }} from "./discovery.js";
{tool_imports}

const server = new MCPServer({{
  name: {json.dumps(self.design.server_name)},
  version: "1.0.0",
  description: {json.dumps(self.design.server_description)},
}});

{tool_registrations}

// /.well-known/mcp discovery resource (CONTRACT C-01..C-03)
server.resource(
  {{
    name: "mcp-discovery",
    uri: "/.well-known/mcp",
    title: "MCP Discovery",
    description: "Server discovery metadata: tool count, tool groups, and disclosure levels.",
  }},
  async () => object(getDiscoveryInfo())
);

export default server;
'''
        self._write("src/server.ts", content)

    def _emit_tools(self) -> None:
        for tool in self.design.tools:
            params_schema = self._render_zod_schema(tool)
            annotations_line = self._render_annotations(tool)
            call_code = self._render_call(tool)

            content = f'''/**
 * Tool: {tool.name}
 * {tool.description}
 */
import {{ z }} from "zod";
import {{ compact }} from "../compact.js";
import {{ recordCall }} from "../telemetry.js";

export const config = {{
  name: {json.dumps(tool.name)},
  description: {json.dumps(tool.description)},
  inputSchema: z.object({{
{params_schema}
  }}),
{annotations_line}}};

export const handler = async (params: any): Promise<any> => {{
  const start = Date.now();
  try {{
{call_code}
  }} finally {{
    recordCall({json.dumps(tool.name)}, Date.now() - start, "ok");
  }}
}};
'''
            self._write(f"src/tools/{tool.name}.ts", content)

    def _http_annotations(self, tool) -> dict | None:
        """Best-effort MCP tool annotations, derived from HTTP method semantics."""
        impl = tool.impl
        if impl.strategy != "http_call" or not impl.http_method:
            return None
        method = impl.http_method.upper()
        if method == "GET":
            return {"readOnlyHint": True, "destructiveHint": False, "openWorldHint": True}
        if method == "DELETE":
            return {"readOnlyHint": False, "destructiveHint": True, "openWorldHint": True}
        if method in ("POST", "PUT", "PATCH"):
            return {"readOnlyHint": False, "destructiveHint": False, "openWorldHint": True}
        return None

    def _render_annotations(self, tool) -> str:
        annotations = self._http_annotations(tool)
        if not annotations:
            return ""
        fields = ", ".join(f"{k}: {str(v).lower()}" for k, v in annotations.items())
        return f"  annotations: {{ {fields} }},\n"

    def _render_zod_schema(self, tool) -> str:
        lines = []
        for p in tool.parameters:
            z_type = self._to_zod_type(p.type)
            if not p.required:
                z_type = f"{z_type}.optional()"
            lines.append(
                f"    {json.dumps(p.name)}: {z_type}.describe({json.dumps(p.description)}),"
            )
        return "\n".join(lines)

    def _render_call(self, tool) -> str:
        impl = tool.impl

        if impl.strategy == "http_call" and impl.http_method and impl.http_path:
            base_url_env = f"{self.design.server_name.upper().replace('-','_')}_BASE_URL"
            path = impl.http_path
            method = impl.http_method.upper()
            constants = json.dumps(dict(impl.http_query_constants))
            param_meta = {}
            for p in tool.parameters:
                if p.name == "verbose":
                    continue
                mapping = impl.arg_mapping.get(p.name, {})
                style = mapping.get("style") or getattr(p, "location", "") or "query"
                if style not in {"path", "body", "query"}:
                    style = "query"
                param_meta[p.name] = {
                    "style": style,
                    "apiName": mapping.get("api_name") or getattr(p, "api_name", "") or p.name,
                }
            param_meta_json = json.dumps(param_meta)
            return f'''    const baseUrl = process.env["{base_url_env}"] ?? "http://localhost:8000";
    let path = {json.dumps(path)};
    const bodyFields: Record<string, unknown> = {{}};
    const queryParams: Record<string, string> = {{}};
    const paramMeta: Record<string, {{ style: string; apiName: string }}> = {param_meta_json};
    for (const [k, v] of Object.entries(params)) {{
      if (v == null || k === "verbose") continue;
      const meta = paramMeta[k] ?? {{ style: "query", apiName: k }};
      if (meta.style === "path") {{
        // Substitute into the path string before constructing URL — the URL
        // constructor percent-encodes "{{" and "}}" immediately, so a literal
        // "{{param}}" placeholder no longer exists in .pathname afterward.
        path = path.replace(`{{${{meta.apiName}}}}`, encodeURIComponent(String(v)));
      }} else if (meta.style === "body") {{
        bodyFields[meta.apiName] = v;
      }} else {{
        queryParams[meta.apiName] = String(v);
      }}
    }}
    const url = new URL(`${{baseUrl}}${{path}}`);
    for (const [k, v] of Object.entries(queryParams)) {{
      url.searchParams.set(k, v);
    }}
    for (const [k, v] of Object.entries({constants})) {{
      url.searchParams.set(k, String(v));
    }}
    const hasBody = Object.keys(bodyFields).length > 0;
    const resp = await fetch(url.toString(), {{
      method: "{method}",
      headers: hasBody ? {{ "Content-Type": "application/json" }} : undefined,
      body: hasBody ? JSON.stringify(bodyFields) : undefined,
    }});
    if (!resp.ok) throw new Error(`HTTP ${{resp.status}}: ${{await resp.text()}}`);
    const result = await resp.json();
    const payload = params.verbose ? {{ data: result, _meta: {{ status: resp.status }} }} : compact(result);
    return {{ content: [{{ type: "text" as const, text: JSON.stringify(payload) }}], structuredContent: payload }};'''

        if impl.strategy == "cli_subcommand" and impl.cli_subcommand:
            bin_env = f"{self.design.server_name.upper().replace('-','_')}_BIN"
            default_bin = self.design.server_name
            return f'''    const {{ spawn }} = await import("node:child_process");
    const binary = process.env["{bin_env}"] ?? "{default_bin}";
    const args: string[] = ["{impl.cli_subcommand}"];
    for (const [k, v] of Object.entries(params)) {{
      if (v == null || k === "verbose") continue;
      const flag = `--${{k.replace(/_/g, "-")}}`;
      if (typeof v === "boolean") {{ if (v) args.push(flag); }}
      else args.push(flag, String(v));
    }}
    const result: any = await new Promise((resolve, reject) => {{
      const proc = spawn(binary, args);
      let stdout = "", stderr = "";
      proc.stdout.on("data", (d: Buffer) => stdout += d.toString());
      proc.stderr.on("data", (d: Buffer) => stderr += d.toString());
      proc.on("close", (code: number) => resolve({{ stdout, stderr, returncode: code }}));
      proc.on("error", reject);
    }});
    const payload = params.verbose ? result : compact({{ output: result.stdout || result.stderr, returncode: result.returncode }});
    return {{ content: [{{ type: "text" as const, text: JSON.stringify(payload) }}], structuredContent: payload }};'''

        if impl.strategy == "grpc_call" and impl.grpc_service and impl.grpc_method:
            message = (
                f"gRPC tool '{tool.name}' ({impl.grpc_service}.{impl.grpc_method}) requires a "
                "TypeScript gRPC client. Generate stubs (e.g. via @grpc/proto-loader), configure "
                f"{self.design.server_name.upper().replace('-', '_')}_GRPC_TARGET, and wire the client here."
            )
            return f'''    return {{ isError: true, content: [{{ type: "text" as const, text: {json.dumps(message)} }}] }};'''

        message = (
            f"Tool '{tool.name}' has no executable strategy. "
            "Configure a data source (OpenAPI/gRPC) or implement this tool manually."
        )
        return f'''    return {{ isError: true, content: [{{ type: "text" as const, text: {json.dumps(message)} }}] }};'''

    def _to_zod_type(self, t: str) -> str:
        mapping = {
            "string": "z.string()",
            "integer": "z.number().int()",
            "boolean": "z.boolean()",
            "array": "z.array(z.unknown())",
            "object": "z.record(z.unknown())",
            "number": "z.number()",
        }
        return mapping.get(t, "z.string()")

    def _emit_discovery(self) -> None:
        tool_list = json.dumps(
            [{"name": t.name, "description": t.description[:80]} for t in self.design.tools],
            indent=2,
        )
        groups = json.dumps(
            [{"name": g.name, "disclosure_level": g.disclosure_level} for g in self.design.tool_groups],
            indent=2,
        )
        content = f'''/**
 * Discovery endpoint data (CONTRACT C-01..C-03)
 */

const TOOLS: {{ name: string; description: string }}[] = {tool_list};
const GROUPS: {{ name: string; disclosure_level: string }}[] = {groups};

export function getDiscoveryInfo() {{
  return {{
    server_name: {json.dumps(self.design.server_name)},
    version: "1.0.0",
    tool_count: TOOLS.length,
    tool_groups: GROUPS,
    tools: TOOLS,
  }};
}}
'''
        self._write("src/discovery.ts", content)

    def _emit_telemetry(self) -> None:
        content = '''/**
 * Anonymized per-call telemetry (CONTRACT C-19, C-20)
 * Logs tool name, latency, and status only. Never logs parameter values.
 * Set MCP_TELEMETRY_ENDPOINT to enable remote reporting.
 */

const ENDPOINT = process.env["MCP_TELEMETRY_ENDPOINT"] ?? "";

export function recordCall(tool: string, latencyMs: number, status: string): void {
  console.error(JSON.stringify({ tool, latency_ms: latencyMs, status }));
  if (ENDPOINT) {
    sendRemote(tool, latencyMs, status).catch(() => {}); // must never break tool execution
  }
}

async function sendRemote(tool: string, latencyMs: number, status: string): Promise<void> {
  await fetch(ENDPOINT, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ tool, latency_ms: latencyMs, status }),
    signal: AbortSignal.timeout(1000),
  });
}
'''
        self._write("src/telemetry.ts", content)

    def _emit_dockerfile(self) -> None:
        content = f'''# Generated Dockerfile for {self.design.server_name} (TypeScript / mcp-use)
# CONTRACT C-17, C-18: no embedded secrets; reads API keys from environment at runtime.
FROM node:22-slim

WORKDIR /app

COPY package*.json ./
RUN npm ci --omit=dev

COPY . .
RUN npm run build

EXPOSE 8000

CMD ["npm", "run", "start"]
'''
        self._write("Dockerfile", content)

    def _emit_package_json(self) -> None:
        pkg = {
            "name": self.design.server_name,
            "version": "1.0.0",
            "description": self.design.server_description[:80],
            "type": "module",
            "scripts": {
                "dev": "mcp-use dev --entry src/server.ts",
                "build": "mcp-use build --entry src/server.ts",
                "start": "mcp-use start --host 0.0.0.0 --port 8000",
                "typecheck": "tsc --noEmit",
            },
            "dependencies": {
                "mcp-use": "^2.5.0",
                "zod": "^4.0.0",
            },
            "devDependencies": {
                "typescript": "^5.7.0",
                "@types/node": "^22.0.0",
            },
        }
        self._write("package.json", json.dumps(pkg, indent=2))

    def _emit_tsconfig(self) -> None:
        tsconfig = {
            "compilerOptions": {
                "target": "ES2022",
                "module": "ESNext",
                "moduleResolution": "Bundler",
                "strict": True,
                "esModuleInterop": True,
                "skipLibCheck": True,
                "noEmit": True,
            },
            "include": ["src/**/*"],
            "exclude": ["node_modules", "dist"],
        }
        self._write("tsconfig.json", json.dumps(tsconfig, indent=2))

    _COMPACT_TS = '''/**
 * Return a token-friendly subset of data. Full payload available via verbose=true.
 */
export function compact(data: unknown, depth = 0): unknown {
  if (depth > 3) return data;
  if (Array.isArray(data)) {
    return data.slice(0, 10).map((item) => compact(item, depth + 1));
  }
  if (data && typeof data === "object") {
    return Object.fromEntries(
      Object.entries(data as Record<string, unknown>)
        .slice(0, 20)
        .map(([k, v]) => [k, compact(v, depth + 1)]),
    );
  }
  if (typeof data === "string" && data.length > 300) {
    return data.slice(0, 300) + "…";
  }
  return data;
}
'''

    def _emit_compact(self) -> None:
        self._write("src/compact.ts", self._COMPACT_TS)
