/**
 * Skybridge MCP + ChatGPT App server for spotify-playlist-generator.
 * Generated by mcp-anything, then implemented against the Spotify Web API.
 */
import { McpServer } from "skybridge/server";
import { z } from "zod";
import { recordCall } from "./telemetry.js";
import { getDiscoveryInfo } from "./discovery.js";

const SPOTIFY_API = "https://api.spotify.com/v1";
const SPOTIFY_ACCOUNTS = "https://accounts.spotify.com";
const DEFAULT_SCOPES = [
  "playlist-modify-private",
  "playlist-modify-public",
  "playlist-read-private",
  "user-read-private",
];

type SpotifyImage = {
  url?: string;
  width?: number | null;
  height?: number | null;
};

type SpotifyArtist = {
  name: string;
  external_urls?: { spotify?: string };
};

type SpotifyTrack = {
  id: string;
  name: string;
  uri: string;
  duration_ms: number;
  explicit?: boolean;
  popularity?: number;
  preview_url?: string | null;
  external_urls?: { spotify?: string };
  artists: SpotifyArtist[];
  album: {
    name: string;
    images?: SpotifyImage[];
    external_urls?: { spotify?: string };
  };
};

type PlaylistTrack = {
  id: string;
  uri: string;
  name: string;
  duration_ms: number;
  duration: string;
  singers: string[];
  album: string;
  cover_url: string;
  spotify_url: string;
  explicit: boolean;
};

const server = new McpServer({
  name: "spotify-playlist-generator",
  version: "1.0.0",
  description:
    "Generate Spotify playlists from a target duration and mood or vibe, with track artwork, names, durations, and artists.",
});

function env(name: string): string {
  return process.env[name] ?? "";
}

function jsonTool(result: unknown) {
  return { content: JSON.stringify(result, null, 2) };
}

function requireEnv(name: string): string {
  const value = env(name);
  if (!value) {
    throw new Error(`Missing ${name}. Set it in the server environment.`);
  }
  return value;
}

function normalizeRedirectUri(redirectUri?: string): string {
  return redirectUri || env("SPOTIFY_REDIRECT_URI") || "http://127.0.0.1:8888/callback";
}

function basicAuth(clientId: string, clientSecret: string): string {
  return Buffer.from(`${clientId}:${clientSecret}`).toString("base64");
}

async function tokenRequest(body: URLSearchParams): Promise<any> {
  const clientId = requireEnv("SPOTIFY_CLIENT_ID");
  const clientSecret = requireEnv("SPOTIFY_CLIENT_SECRET");
  const resp = await fetch(`${SPOTIFY_ACCOUNTS}/api/token`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${basicAuth(clientId, clientSecret)}`,
      "Content-Type": "application/x-www-form-urlencoded",
    },
    body,
  });

  const text = await resp.text();
  const payload = text ? JSON.parse(text) : {};
  if (!resp.ok) {
    throw new Error(`Spotify token request failed (${resp.status}): ${payload.error_description ?? text}`);
  }
  return payload;
}

async function getAccessToken(needsUserToken: boolean): Promise<string> {
  const staticToken = env("SPOTIFY_ACCESS_TOKEN");
  if (staticToken) {
    return staticToken;
  }

  const refreshToken = env("SPOTIFY_REFRESH_TOKEN");
  if (refreshToken) {
    const payload = await tokenRequest(new URLSearchParams({
      grant_type: "refresh_token",
      refresh_token: refreshToken,
    }));
    return payload.access_token;
  }

  if (needsUserToken) {
    throw new Error(
      "Creating playlists requires a user OAuth token. Set SPOTIFY_ACCESS_TOKEN or SPOTIFY_REFRESH_TOKEN, or run setup_spotify_oauth and exchange_spotify_code.",
    );
  }

  const payload = await tokenRequest(new URLSearchParams({ grant_type: "client_credentials" }));
  return payload.access_token;
}

async function spotifyFetch<T>(
  path: string,
  options: RequestInit = {},
  needsUserToken = false,
): Promise<T> {
  const token = await getAccessToken(needsUserToken);
  const resp = await fetch(`${SPOTIFY_API}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      ...(options.body ? { "Content-Type": "application/json" } : {}),
      ...(options.headers ?? {}),
    },
  });

  const text = await resp.text();
  const payload = text ? JSON.parse(text) : {};
  if (!resp.ok) {
    const message = payload?.error?.message ?? payload?.error_description ?? text;
    throw new Error(`Spotify API failed (${resp.status}) ${path}: ${message}`);
  }
  return payload as T;
}

function moodSearchTerms(mood: string): string[] {
  const lowered = mood.toLowerCase();
  const presets: Array<[RegExp, string[]]> = [
    [/workout|gym|run|running|cardio|hype|energy/, ["workout", "dance", "pop", "hip hop", "edm"]],
    [/focus|study|deep work|coding|concentration/, ["focus", "ambient", "lofi", "instrumental", "minimal"]],
    [/chill|calm|relax|soft|cozy/, ["chill", "acoustic", "indie", "r&b", "soul"]],
    [/sad|melancholy|heartbreak|rain|rainy/, ["sad", "indie", "acoustic", "folk", "piano"]],
    [/party|club|dance|celebrate/, ["party", "dance", "pop", "house", "latin"]],
    [/romantic|date|love/, ["romantic", "soul", "r&b", "jazz", "pop"]],
    [/drive|road|night|late/, ["night drive", "synthwave", "indie pop", "alternative", "electronic"]],
  ];

  for (const [pattern, terms] of presets) {
    if (pattern.test(lowered)) {
      return [mood, ...terms];
    }
  }
  return [mood, `${mood} pop`, `${mood} indie`, `${mood} mood`, "fresh finds"];
}

function formatDuration(ms: number): string {
  const totalSeconds = Math.round(ms / 1000);
  const minutes = Math.floor(totalSeconds / 60);
  const seconds = totalSeconds % 60;
  return `${minutes}:${seconds.toString().padStart(2, "0")}`;
}

function compactTrack(track: SpotifyTrack): PlaylistTrack {
  return {
    id: track.id,
    uri: track.uri,
    name: track.name,
    duration_ms: track.duration_ms,
    duration: formatDuration(track.duration_ms),
    singers: track.artists.map((artist) => artist.name),
    album: track.album.name,
    cover_url: track.album.images?.[0]?.url ?? "",
    spotify_url: track.external_urls?.spotify ?? "",
    explicit: Boolean(track.explicit),
  };
}

async function searchTracks(query: string, market: string): Promise<SpotifyTrack[]> {
  const params = new URLSearchParams({
    q: query,
    type: "track",
    market,
    limit: "10",
  });
  const result = await spotifyFetch<{ tracks?: { items?: SpotifyTrack[] } }>(
    `/search?${params.toString()}`,
  );
  return result.tracks?.items ?? [];
}

async function collectCandidates(moodVibe: string, market: string): Promise<SpotifyTrack[]> {
  const seen = new Set<string>();
  const tracks: SpotifyTrack[] = [];
  for (const term of moodSearchTerms(moodVibe)) {
    const found = await searchTracks(term, market);
    for (const track of found) {
      if (!track?.id || seen.has(track.id)) {
        continue;
      }
      seen.add(track.id);
      tracks.push(track);
    }
  }
  return tracks.sort((a, b) => (b.popularity ?? 0) - (a.popularity ?? 0));
}

function selectForDuration(candidates: SpotifyTrack[], targetMs: number): SpotifyTrack[] {
  const selected: SpotifyTrack[] = [];
  let totalMs = 0;
  for (const track of candidates) {
    if (selected.length >= 100) {
      break;
    }
    if (totalMs >= targetMs) {
      break;
    }
    selected.push(track);
    totalMs += track.duration_ms;
  }
  return selected;
}

async function createSpotifyPlaylist(args: {
  playlistName: string;
  description: string;
  isPublic: boolean;
  trackUris: string[];
}) {
  const playlist = await spotifyFetch<any>(
    "/me/playlists",
    {
      method: "POST",
      body: JSON.stringify({
        name: args.playlistName,
        description: args.description,
        public: args.isPublic,
      }),
    },
    true,
  );

  for (let i = 0; i < args.trackUris.length; i += 100) {
    const uris = args.trackUris.slice(i, i + 100);
    await spotifyFetch(
      `/playlists/${playlist.id}/items`,
      {
        method: "POST",
        body: JSON.stringify({ uris }),
      },
      true,
    );
  }
  return playlist;
}

server.registerTool(
  {
    name: "setup_spotify_oauth",
    description:
      "Returns a Spotify authorization URL for granting playlist write access to this MCP server. Use it before exchanging the callback code for a refresh token.",
    inputSchema: {
      redirect_uri: z.string().optional().describe("Redirect URI registered in the Spotify developer dashboard."),
      state: z.string().optional().describe("Optional OAuth state value for CSRF protection."),
      scopes: z.array(z.string()).optional().describe("OAuth scopes to request. Defaults to playlist write and profile scopes."),
    },
  },
  async (args: any) => {
    const start = Date.now();
    try {
      const clientId = requireEnv("SPOTIFY_CLIENT_ID");
      const redirectUri = normalizeRedirectUri(args.redirect_uri);
      const scopes = Array.isArray(args.scopes) && args.scopes.length ? args.scopes : DEFAULT_SCOPES;
      const authUrl = new URL(`${SPOTIFY_ACCOUNTS}/authorize`);
      authUrl.search = new URLSearchParams({
        response_type: "code",
        client_id: clientId,
        scope: scopes.join(" "),
        redirect_uri: redirectUri,
        ...(args.state ? { state: String(args.state) } : {}),
      }).toString();

      return jsonTool({
        authorization_url: authUrl.toString(),
        redirect_uri: redirectUri,
        scopes,
        next_step:
          "Open authorization_url, approve access, copy the callback code, then call exchange_spotify_code with that code.",
      });
    } finally {
      recordCall("setup_spotify_oauth", Date.now() - start, "ok");
    }
  },
);

server.registerTool(
  {
    name: "exchange_spotify_code",
    description:
      "Exchanges a Spotify OAuth callback code for access and refresh tokens. Store the returned refresh token as SPOTIFY_REFRESH_TOKEN for future runs.",
    inputSchema: {
      code: z.string().describe("OAuth code from the Spotify redirect callback."),
      redirect_uri: z.string().optional().describe("Redirect URI used when creating the authorization URL."),
    },
  },
  async (args: any) => {
    const start = Date.now();
    try {
      const payload = await tokenRequest(new URLSearchParams({
        grant_type: "authorization_code",
        code: String(args.code),
        redirect_uri: normalizeRedirectUri(args.redirect_uri),
      }));

      return jsonTool({
        access_token: payload.access_token,
        expires_in: payload.expires_in,
        refresh_token: payload.refresh_token,
        token_type: payload.token_type,
        setup:
          "Export SPOTIFY_REFRESH_TOKEN with the refresh_token value so the server can refresh access without storing secrets in files.",
      });
    } finally {
      recordCall("exchange_spotify_code", Date.now() - start, "ok");
    }
  },
);

server.registerTool(
  {
    name: "generate_spotify_playlist",
    description:
      "Generates a Spotify track list from a requested duration and mood/vibe, returning artwork, track names, durations, and singers; optionally creates the playlist in Spotify.",
    inputSchema: {
      duration_minutes: z.number().min(5).max(480).describe("Target playlist duration in minutes."),
      mood_vibe: z.string().min(2).describe("Mood or vibe, such as rainy indie, workout, chill focus, or late-night drive."),
      market: z.string().length(2).optional().describe("ISO 3166-1 alpha-2 market code, default US."),
      playlist_name: z.string().optional().describe("Name to use when create_playlist is true."),
      create_playlist: z.boolean().optional().describe("Create the playlist in the user's Spotify account."),
      public: z.boolean().optional().describe("Whether the created Spotify playlist should be public."),
    },
  },
  async (args: any) => {
    const start = Date.now();
    try {
      const durationMinutes = Number(args.duration_minutes);
      const moodVibe = String(args.mood_vibe ?? "").trim();
      const market = String(args.market ?? "US").toUpperCase();
      const targetMs = durationMinutes * 60 * 1000;
      if (!moodVibe) {
        throw new Error("mood_vibe is required.");
      }

      const candidates = await collectCandidates(moodVibe, market);
      const selected = selectForDuration(candidates, targetMs);
      if (!selected.length) {
        throw new Error(`No Spotify tracks found for "${moodVibe}" in market ${market}.`);
      }

      const tracks = selected.map(compactTrack);
      const totalMs = tracks.reduce((sum, track) => sum + track.duration_ms, 0);
      const playlistName = String(args.playlist_name || `${moodVibe} - ${durationMinutes} min`);
      let createdPlaylist = null;

      if (args.create_playlist) {
        createdPlaylist = await createSpotifyPlaylist({
          playlistName,
          description: `Generated by MCP-Anything for vibe "${moodVibe}" and target ${durationMinutes} minutes.`,
          isPublic: Boolean(args.public),
          trackUris: tracks.map((track) => track.uri),
        });
      }

      return jsonTool({
        playlist_name: playlistName,
        mood_vibe: moodVibe,
        requested_duration_minutes: durationMinutes,
        actual_duration_ms: totalMs,
        actual_duration: formatDuration(totalMs),
        delta_ms: totalMs - targetMs,
        market,
        created_playlist: createdPlaylist
          ? {
              id: createdPlaylist.id,
              uri: createdPlaylist.uri,
              spotify_url: createdPlaylist.external_urls?.spotify ?? "",
              public: createdPlaylist.public,
            }
          : null,
        tracks,
      });
    } finally {
      recordCall("generate_spotify_playlist", Date.now() - start, "ok");
    }
  },
);

server.resource("mcp-discovery", "/.well-known/mcp", async () => {
  return {
    contents: [{
      uri: "/.well-known/mcp",
      mimeType: "application/json",
      text: JSON.stringify(getDiscoveryInfo()),
    }],
  };
});

server.run().catch(console.error);
